# Generated by Django 4.0.6 on 2022-08-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djpieuvre.mixins


class Migration(migrations.Migration):

    replaces = [
        ("djpieuvre", "0001_initial"),
        ("djpieuvre", "0002_auto_20211119_1727"),
        ("djpieuvre", "0003_auto_20211123_0714"),
        ("djpieuvre", "0004_alter_pieuvretask_unique_together"),
        ("djpieuvre", "0005_alter_pieuvretask_process"),
        ("djpieuvre", "0006_alter_pieuvretask_options"),
        ("djpieuvre", "0007_alter_pieuvreprocess_workflow_name"),
    ]

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PieuvreProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("workflow_name", models.CharField(max_length=255)),
                ("workflow_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("state", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "workflow_name")},
                "ordering": ("created_at",),
            },
            bases=(djpieuvre.mixins.WorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name="PieuvreTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("started", "Started"),
                            ("done", "Done"),
                        ],
                        default="created",
                        max_length=128,
                    ),
                ),
                ("name", models.TextField()),
                ("task", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("groups", models.ManyToManyField(to="auth.group")),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="djpieuvre.pieuvreprocess",
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": set(),
                "ordering": ("-created_at",),
            },
        ),
    ]
