# Generated by Django 3.2.8 on 2021-11-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("djpieuvre", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pieuvreprocess",
            unique_together={("content_type", "object_id", "workflow_name")},
        ),
        migrations.AlterUniqueTogether(
            name="pieuvretask",
            unique_together={("process", "task")},
        ),
    ]
