# Generated by Django 3.2.9 on 2021-11-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpieuvre', '0002_auto_20211119_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieuvreprocess',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='pieuvretask',
            options={'ordering': ('created_at',)},
        ),
    ]
