# Generated by Django 3.2.8 on 2022-01-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djpieuvre", "0005_alter_pieuvretask_process"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pieuvretask",
            options={"ordering": ("-created_at",)},
        ),
    ]
