# Generated by Django 4.0.6 on 2022-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpieuvre", "0006_alter_pieuvretask_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pieuvreprocess",
            name="workflow_name",
            field=models.CharField(max_length=255),
        ),
    ]
