# Generated by Django 3.2.9 on 2021-11-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myprocess",
            options={"permissions": [("access_my_first_workflow2", "comment")]},
        ),
    ]
