# Generated by Django 3.2.8 on 2022-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_myprocess_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myprocess",
            options={
                "permissions": [
                    ("access_my_first_workflow2_write", "comment"),
                    ("access_my_first_workflow2_read", "read"),
                ]
            },
        ),
    ]
